version: "2"
run:
  go: "1.24"
  tests: false
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - makezero
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unused
    - misspell
  settings:
    staticcheck:
      checks:
        - all
        - "-SA1019" # disable error for using deprecated methods
        - "-ST1003" # disable case for var names (ex: myId->myID)
        - "-QF1008" # allow to call embedded structs explicitly
    gocritic:
      disabled-checks:
        - captLocal
        - commentFormatting
    nolintlint:
      require-explanation: true
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - -test
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
