{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chorus.serviceAccountName" . }}
  labels:
    {{- include "chorus.labels" . | nindent 4 }}
  {{- with (include "chorus.annotations" (list .Values.serviceAccount.annotations .)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
