{{- if and .Values.agent.enabled .Values.agent.config.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: agent
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
  jobLabel: app
{{- end }}
