{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chorus.fullname" . }}-worker-metrics
  labels:
    {{- include "chorus.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    chorus.clyso.com/metrics: "true"
  {{- with (include "chorus.annotations" (list dict .)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "chorus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  ports:
    - name: metrics
      port: {{ include "chorus.metricsPort" . }}
      targetPort: metrics
{{- end }}
