// Code generated by "stringer -type Method"; DO NOT EDIT.

package swift

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedMethod-0]
	_ = x[GetInfo-1]
	_ = x[GetAccount-2]
	_ = x[PostAccount-3]
	_ = x[HeadAccount-4]
	_ = x[DeleteAccount-5]
	_ = x[GetContainer-6]
	_ = x[PutContainer-7]
	_ = x[PostContainer-8]
	_ = x[HeadContainer-9]
	_ = x[DeleteContainer-10]
	_ = x[GetObject-11]
	_ = x[PutObject-12]
	_ = x[CopyObject-13]
	_ = x[DeleteObject-14]
	_ = x[HeadObject-15]
	_ = x[PostObject-16]
	_ = x[GetEndpoints-17]
}

const _Method_name = "UndefinedMethodGetInfoGetAccountPostAccountHeadAccountDeleteAccountGetContainerPutContainerPostContainerHeadContainerDeleteContainerGetObjectPutObjectCopyObjectDeleteObjectHeadObjectPostObjectGetEndpoints"

var _Method_index = [...]uint8{0, 15, 22, 32, 43, 54, 67, 79, 91, 104, 117, 132, 141, 150, 160, 172, 182, 192, 204}

func (i Method) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Method_index)-1 {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[idx]:_Method_index[idx+1]]
}
