export const AUTH_CLIENT_ID = 'dashboard';

export const TOKEN_REFRESH_TIMEOUT_MINUTES = 3;
export const IDLE_TIMEOUT_MINUTES = 20;
export const IDLE_MESSAGE_TIMEOUT_MINUTES = 19.5;
export const IDLE_MESSAGE_DURATION_MINUTES =
  IDLE_TIMEOUT_MINUTES - IDLE_MESSAGE_TIMEOUT_MINUTES;
